---
title: "Data 100 - Final Project"
output: html_notebook
runtime: shiny
---

```{r echo=FALSE}
# install.packages ( "maps" )
# install.packages( "party" )
# install.packages("shiny")
# install.packages("ggplot2")

require(ggplot2)
require(maps)

library(party)
library(shiny)
```


```{r echo=FALSE }
data_2011 <- read.csv ( "2011.csv", header = TRUE, na.strings = c ( "", "NA" ) )
data_2012 <- read.csv ( "2012.csv", header = TRUE, na.strings = c ( "", "NA" ) )
data_2013 <- read.csv ( "2013.csv", header = TRUE, na.strings = c ( "", "NA" ) )
data_2014 <- read.csv ( "2014.csv", header = TRUE, na.strings = c ( "", "NA" ) )
data_2015 <- read.csv ( "2015.csv", header = TRUE, na.strings = c ( "", "NA" ) )
data_2016 <- read.csv ( "2016.csv", header = TRUE, na.strings = c ( "", "NA" ) )
data_2017 <- read.csv ( "2017.csv", header = TRUE, na.strings = c ( "", "NA" ) )
```


```{r echo=FALSE}
language_use2011 <- c ( NROW ( data_2011 [ !is.na ( data_2011$Which.languages.are.you.proficient.in. ), ] ), # Java
                        NROW ( data_2011 [ !is.na ( data_2011$X.18 ), ] ), # JavaScript
                        NROW ( data_2011 [ !is.na ( data_2011$X.20 ), ] ), # PHP
                        NROW ( data_2011 [ !is.na ( data_2011$X.21 ), ] ), # Python
                        NROW ( data_2011 [ !is.na ( data_2011$X.22 ), ] ), # Ruby
                        NROW ( data_2011 [ !is.na ( data_2011$X.23 ), ] ), # SQL
                        NROW ( data_2011 [ !is.na ( data_2011$X.24 ), ] ), # C#
                        NROW ( data_2011 [ !is.na ( data_2011$X.25 ), ] ), # C++
                        NROW ( data_2011 [ !is.na ( data_2011$X.26 ), ] ), # C
                        0, # Objective-C
                        0 ) # Node-JS

language_use2012 <- c ( NROW ( data_2012 [ !is.na ( data_2012$Which.languages.are.you.proficient.in. ), ] ), # Java
                        NROW ( data_2012 [ !is.na ( data_2012$X.11 ), ] ), # JavaScript
                        NROW ( data_2012 [ !is.na ( data_2012$X.13 ), ] ), # PHP
                        NROW ( data_2012 [ !is.na ( data_2012$X.14 ), ] ), # Python
                        NROW ( data_2012 [ !is.na ( data_2012$X.16 ), ] ), # Ruby
                        NROW ( data_2012 [ !is.na ( data_2012$X.17 ), ] ), # SQL
                        NROW ( data_2012 [ !is.na ( data_2012$X.18 ), ] ), # C#
                        NROW ( data_2012 [ !is.na ( data_2012$X.19 ), ] ), # C++
                        NROW ( data_2012 [ !is.na ( data_2012$X.20 ), ] ), # C
                        NROW ( data_2012 [ !is.na ( data_2012$X.15 ), ] ), # Objective-C
                        0 ) # Node-JS
                        
language_use2013 <- c ( NROW ( data_2013 [ !is.na ( data_2013$X.42 ), ] ), # Java
                        NROW ( data_2013 [ !is.na ( data_2013$X.43 ), ] ), # JavaScript
                        NROW ( data_2013 [ !is.na ( data_2013$X.48 ), ] ), # PHP
                        NROW ( data_2013 [ !is.na ( data_2013$X.49 ), ] ), # Python
                        NROW ( data_2013 [ !is.na ( data_2013$X.50 ), ] ), # Ruby
                        NROW ( data_2013 [ !is.na ( data_2013$X.51 ), ] ), # SQL
                        NROW ( data_2013 [ !is.na ( data_2013$X.41 ), ] ), # C#
                        NROW ( data_2013 [ !is.na ( data_2013$X.40 ), ] ), # C++
                        NROW ( data_2013 [ !is.na ( data_2013$Which.of.the.following.languages.or.technologies.have.you.used.significantly.in.the.past.year. ), ] ), # C
                        NROW ( data_2013 [ !is.na ( data_2013$X.47 ), ] ), # Objective-C
                        NROW ( data_2013 [ !is.na ( data_2013$X.46 ), ] ) ) # Node-JS
                
language_use2014 <- c ( NROW ( data_2014 [ !is.na ( data_2014$X.27 ), ] ), # Java
                        NROW ( data_2014 [ !is.na ( data_2014$X.28 ), ] ), # JavaScript
                        NROW ( data_2014 [ !is.na ( data_2014$X.31 ), ] ), # PHP
                        NROW ( data_2014 [ !is.na ( data_2014$X.32 ), ] ), # Python
                        NROW ( data_2014 [ !is.na ( data_2014$X.33 ), ] ), # Ruby
                        NROW ( data_2014 [ !is.na ( data_2014$X.34 ), ] ), # SQL
                        NROW ( data_2014 [ !is.na ( data_2014$X.26 ), ] ), # C#
                        NROW ( data_2014 [ !is.na ( data_2014$X.25 ), ] ), # C++
                        NROW ( data_2014 [ !is.na ( data_2014$X.24 ), ] ), # C
                        NROW ( data_2014 [ !is.na ( data_2014$X.30 ), ] ), # Objective-C
                        NROW ( data_2014 [ !is.na ( data_2014$X.29 ), ] ) ) # Node-Js

language_use2015 <- c ( NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..Java ), ] ), # Java
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..JavaScript ), ] ), # JavaScript
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..PHP ), ] ), # PHP
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..Python ), ] ), # Python
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..Ruby ), ] ), # Ruby
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..SQL ), ] ), # SQL
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..C. ), ] ), # C#
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..C.. ), ] ), # C++
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..C ), ] ), # C
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..Objective.C ), ] ), # OBjective-C
                        NROW ( data_2015 [ !is.na ( data_2015$Current.Lang...Tech..Node.js ), ] ) ) # Node-JS
  
langs <- c ( "Java", "JavaScript", "PHP", "Python", "Ruby", "SQL", "C#", "C++", "C", "Objective-C", "Node.js")
language_use2016 <- data.frame ( langs, rep.int ( 0, 11 ), rep ( 2016, 11 ) )  
rownames ( language_use2016 ) <- c ( "Java", "JavaScript", "PHP", "Python", "Ruby", "SQL", "C#", "C++", "C", "Objective-C", "Node.js")

for ( i in data_2016$tech_do ) {
  if ( !is.na ( i ) ) {
    vals <- strsplit ( toString ( i ), "; " )
    vals <- unlist ( vals )
    for ( j in vals ) {
      if ( !is.na ( j ) ) {
        if ( toString ( j ) %in% rownames ( language_use2016 ) ) {
          language_use2016 [ j, 2 ] <- language_use2016 [ j, 2 ] + 1 
        }
      }
    }
  } 
}

language_use2016$rep.int.0..11. <- language_use2016 [ , 2 ] / NROW ( data_2016 )

language_use2017 <- data.frame ( langs, rep.int ( 0, 11 ), rep ( 2017, 11 ) )
rownames ( language_use2017 ) <- c ( "Java", "JavaScript", "PHP", "Python", "Ruby", "SQL", "C#", "C++", "C", "Objective-C", "Node.js")

for ( i in data_2017$HaveWorkedLanguage ) {
  if ( !is.na ( i ) ) {
    vals <- strsplit ( toString ( i ), "; " )
    vals <- unlist ( vals )
    for ( j in vals ) {
      if ( !is.na ( j ) ) {
        if ( toString ( j ) %in% rownames ( language_use2017 ) ) {
          language_use2017 [ j, 2 ] <- language_use2017 [ j, 2 ] + 1 
        }
      }
    }
  } 
}

language_use2017$rep.int.0..11. <- language_use2017 [ , 2 ] / NROW ( data_2017 )

rm ( i, j, vals )

language_use2011 <- data.frame ( langs, language_use2011 / NROW ( data_2011 ), rep ( 2011, 11 ) )
language_use2012 <- data.frame ( langs, language_use2012 / NROW ( data_2012 ), rep ( 2012, 11 ) )
language_use2013 <- data.frame ( langs, language_use2013 / NROW ( data_2013 ), rep ( 2013, 11 ) )
language_use2014 <- data.frame ( langs, language_use2014 / NROW ( data_2014 ), rep ( 2014, 11 ) )
language_use2015 <- data.frame ( langs, language_use2015 / NROW ( data_2015 ), rep ( 2015, 11 ) )

names <- c ( "Language", "Percent", "Year" )
colnames( language_use2011 ) <- names
colnames( language_use2012 ) <- names
colnames( language_use2013 ) <- names
colnames( language_use2014 ) <- names
colnames( language_use2015 ) <- names
colnames( language_use2016 ) <- names
colnames( language_use2017 ) <- names

rm ( langs, names )

language_use <- list ( language_use2011, language_use2012, language_use2013, language_use2014, language_use2015, language_use2016, language_use2017 )
language_use <- do.call ( rbind, language_use )

rm ( language_use2011, language_use2012, language_use2013, language_use2014, language_use2015, language_use2016, language_use2017 )
```

```{r echo=FALSE}
renderPlot ( {
  ggplot ( data = language_use, aes ( x = Year, y = Percent,group = Language  ) ) +
    geom_point ( aes ( color = Language ) ) +
    geom_line ( aes ( color = Language ) )
} )
```

```{r echo=FALSE}
gender_2017 <- data.frame ( data_2017 [ ( ( data_2017$Gender == "Female" | data_2017$Gender == "Male" ) & !is.na ( data_2017$Gender ) ), "Gender" ] )
gender_2017 <- data.frame ( gender_2017, rep ( 2017, NROW ( gender_2017 ) ) )
num_not_null <- NROW ( data_2017 [ !is.na ( data_2017$Gender ), ] )

other <- data.frame ( rep ( "Other", num_not_null - NROW ( gender_2017 ) ), rep ( 2017, num_not_null - NROW ( gender_2017 ) ) )
colnames ( other ) <- c ( "Gender", "Year" )
colnames( gender_2017 ) <- c ( "Gender", "Year" )
gender_2017 <- rbind ( gender_2017, other )

gender_2015 <- data.frame ( data_2015$Gender, rep ( 2015, NROW ( data_2015 ) ) )
gender_2016 <- data.frame ( data_2016$gender, rep ( 2016, NROW ( data_2016 ) ) )
colnames ( gender_2015 ) <- c ( "Gender", "Year" )
colnames ( gender_2016 ) <- c ( "Gender", "Year" )

gender <- list ( gender_2015, gender_2016, gender_2017 )
gender <- do.call ( rbind, gender )

gender <- table( gender )
gender <- data.frame ( gender )
gender <- gender [ gender$Freq != 0 & gender$Gender != "Prefer not to disclose", ]

renderPlot ( {
  ggplot ( data = gender, aes( Year, Freq ) ) +
    geom_bar( aes ( fill = Gender ), position = "dodge", stat = "identity" )
} )

rm ( num_not_null, other, gender_2015, gender_2016, gender_2017 )
```

```{r echo=FALSE}
country <- data_2017$Country
country <- data.frame ( table ( country ) )
country$country <- as.character( country$country )
country$country [ country$country == "United States" ] <- "USA"
country$country [ country$country == "United Kingdom" ] <- "UK"
country$country [ country$country == "Russian Federation" ] <- "Russia"
country <- country [ - c ( 9 ), ] # Remove Antartica
colnames ( country ) <- c ( "region", "freq" )

map.world <- map_data ( "world" )
map.world <- merge( x = map.world, y = country, by = "region", all = TRUE)
map.world <- map.world [ order ( map.world$order ), ]

renderPlot ( {
  ggplot ( ) + 
    theme ( legend.position = "none" ) +
    geom_map( data = map.world, map = map.world, aes ( map_id = region, x = long, y = lat, fill = freq ) ) +
    scale_fill_gradient( low = "green", high = "blue", guide = "colourbar" ) +
    coord_equal ( )
} )

rm ( country )
```

```{r echo=FALSE}
stack <- data_2017

#trying to get language
lang <- stack$HaveWorkedLanguage
spade <- strsplit(as.character(lang), ';')
mixed <- do.call(rbind, spade)
# head(mixed[,1])

stack$PrimaryLanguage <- mixed[,1]
stack$PrimaryLanguage <- as.factor(stack$PrimaryLanguage)
# class(stack$PrimaryLanguage)

stack$SalaryGroup <- ifelse(stack$Salary < 40000, 0, ifelse(stack$Salary > 100000, 2, 1))

stack$SalaryGroup <- as.factor(stack$SalaryGroup)


```

```{r echo=FALSE}


#need a No NA dataset with just salary and gender

stack.Sel <- subset(stack, select = c("PrimaryLanguage", "TabsSpaces", "YearsProgram", "Professional", "MajorUndergrad", "JobSatisfaction", "Salary", "SalaryGroup", "Gender", "Race"))

# head(stack.Sel)
#cleans all NAs
stack.Sel.clean <- stack.Sel[!is.na(stack.Sel),]
#for some reason, NAs in 
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$YearsProgram),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$TabsSpaces),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$PrimaryLanguage),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$Professional),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$JobSatisfaction),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$MajorUndergrad),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$SalaryGroup),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$Gender),]
stack.Sel.clean <- stack.Sel.clean[!is.na(stack.Sel.clean$Race),]

# head(stack.Sel.clean)

#need to simplify Salary
#stack.Sel.clean$SalaryGroup <- ifelse(stack.Sel.clean$Salary <=65000, 0, 
 #                                ifelse(stack.Sel.clean$Salary >130000, 1, 1))
# class(stack.Sel.clean$PrimaryLanguage)

# class(stack.Sel.clean$SalaryGroup)

```

```{r echo=FALSE}

tree1 <- ctree(SalaryGroup ~ PrimaryLanguage + Professional + YearsProgram, data=stack.Sel.clean)
#plot(tree1)

#build a predictor
indices <- sample(2, nrow(stack.Sel.clean), replace = TRUE, prob = c(0.7, 0.3))
stack17.train <- stack.Sel.clean[indices == 1,]
stack17.test <- stack.Sel.clean[indices == 2,]

#SALARY
#stack17.Saldt <- ctree(SalaryGroup ~ YearsProgram + Professional + TabsSpaces + Gender + MajorUndergrad + PrimaryLanguage, data = stack17.train)
stack17.Saldt <- ctree(SalaryGroup ~  MajorUndergrad + PrimaryLanguage + TabsSpaces, data = stack17.train)
# plot(stack17.Saldt)

stack17.Salpredict <- predict(stack17.Saldt, newdata = stack17.test)

Salpred.table <- table("Predicted" = stack17.Salpredict, "Actual" = stack17.test$SalaryGroup)
# Salpred.table

#PRIMARY LANGUAGE
#stack17.Langdt <- ctree(PrimaryLanguage ~ YearsProgram + Professional + TabsSpaces + Gender + MajorUndergrad, data = stack17.train)
stack17.Langdt <- ctree(PrimaryLanguage ~  YearsProgram + Professional + TabsSpaces, data = stack17.train)
# plot(stack17.Langdt)

stack17.LangPredict <- predict(stack17.Langdt, newdata = stack17.test)

LangPred.table <- table("Predicted" = stack17.LangPredict, "Actual" = stack17.test$PrimaryLanguage)
# LangPred.table
```

```{r}
renderPlot({
  plot(stack17.Saldt, main="Salary Decision Tree")
})

Salpred.table

renderPlot({plot(stack17.Langdt, main = "Language Decision Tree")})

LangPred.table
```

```{r echo=FALSE}
#Subset company type and job satisfaction
satisfaction_company_2017 <- subset(data_2017, select = c("CompanyType", "JobSatisfaction"))
#eliminate na
satisfaction_company_2017 <- subset(satisfaction_company_2017, !(is.na(satisfaction_company_2017$CompanyType)) & !(is.na(satisfaction_company_2017$JobSatisfaction)))
satisfaction_company_2017
```
```{r echo=FALSE}
#find the average
satisfaction_avg_2017 <- aggregate(satisfaction_company_2017$JobSatisfaction, by=list(CompanyType=satisfaction_company_2017$CompanyType), FUN = mean)
satisfaction_avg_2017

```


```{r echo=FALSE}
renderPlot ( {
  ggplot(data = satisfaction_avg_2017, aes (x = CompanyType, y = x)) + 
    geom_bar(stat = "identity", aes (fill = CompanyType), show.legend = FALSE) + 
    coord_flip( ylim = c ( 5 : 8 ) ) + 
    labs(title = "Job Satisfaction per Company Type (2017)", y = "Average Job Satisfaction: ( 5 - 8 )", x = "Company Type")
})
```

```{r echo=FALSE}
#subsetting salary and industry for 2016 - 2011 and eliminating na
salary_industry_2016 <- subset(data_2016, select = c("salary_range", "industry"))
salary_industry_2016 <- subset(salary_industry_2016, !is.na(salary_industry_2016$salary_range) & !is.na(salary_industry_2016$industry))

salary_industry_2015 <- subset(data_2015, select = c("Compensation", "Industry"))
salary_industry_2015 <- subset(salary_industry_2015, !is.na(salary_industry_2015$Compensation) & !is.na(salary_industry_2015$Industry))

salary_industry_2014 <- subset(data_2014, select = c("Including.bonus..what.is.your.annual.compensation.in.USD.", "How.would.you.best.describe.the.industry.you.currently.work.in."))
salary_industry_2014 <- subset(salary_industry_2014, !is.na(salary_industry_2014$Including.bonus..what.is.your.annual.compensation.in.USD.) & !is.na(salary_industry_2014$How.would.you.best.describe.the.industry.you.currently.work.in.))
salary_industry_2014 <- subset(salary_industry_2014[-1,])

salary_industry_2013 <- subset(data_2013, select = c("Including.bonus..what.is.your.annual.compensation.in.USD.", "How.would.you.best.describe.the.industry.you.currently.work.in."))
salary_industry_2013 <- subset(salary_industry_2013, !is.na(salary_industry_2013$Including.bonus..what.is.your.annual.compensation.in.USD.) & !is.na(salary_industry_2013$How.would.you.best.describe.the.industry.you.currently.work.in.))
salary_industry_2013 <- subset(salary_industry_2013[-1,])

salary_industry_2012 <- subset(data_2012, select = c("Including.bonus..what.is.your.annual.compensation.in.USD.", "How.would.you.best.describe.the.industry.you.currently.work.in."))
salary_industry_2012 <- subset(salary_industry_2012, !is.na(salary_industry_2012$Including.bonus..what.is.your.annual.compensation.in.USD.) & !is.na(salary_industry_2012$How.would.you.best.describe.the.industry.you.currently.work.in.))
salary_industry_2012 <- subset(salary_industry_2012[-1,])

salary_industry_2011 <- subset(data_2011, select = c("Including.bonus..what.is.your.annual.compensation.in.USD.", "How.would.you.best.describe.the.industry.you.work.in."))
salary_industry_2011 <- subset(salary_industry_2011, !is.na(salary_industry_2011$Including.bonus..what.is.your.annual.compensation.in.USD.) & !is.na(salary_industry_2011$How.would.you.best.describe.the.industry.you.work.in.))
salary_industry_2011 <- subset(salary_industry_2011[-1,])

#rename the columns
new_name <- c("Salary", "Industry")
names(salary_industry_2016) <- new_name
names(salary_industry_2015) <- new_name
names(salary_industry_2014) <- new_name
names(salary_industry_2013) <- new_name
names(salary_industry_2012) <- new_name
names(salary_industry_2011) <- new_name

```

```{r echo=FALSE}
#count how many people are in each category
si_agg_2016 <- aggregate(salary_industry_2016$Industry, by=list(Salary=salary_industry_2016$Salary, Industry=salary_industry_2016$Industry), FUN = length)

si_agg_2015 <- aggregate(salary_industry_2015$Industry, by=list(Salary=salary_industry_2015$Salary, Industry=salary_industry_2015$Industry), FUN = length)

si_agg_2014 <- aggregate(salary_industry_2014$Industry, by=list(Salary=salary_industry_2014$Salary, Industry=salary_industry_2014$Industry), FUN = length)

si_agg_2013 <- aggregate(salary_industry_2013$Industry, by=list(Salary=salary_industry_2013$Salary, Industry=salary_industry_2013$Industry), FUN = length)

si_agg_2012 <- aggregate(salary_industry_2012$Industry, by=list(Salary=salary_industry_2012$Salary, Industry=salary_industry_2012$Industry), FUN = length)

si_agg_2011 <- aggregate(salary_industry_2011$Industry, by=list(Salary=salary_industry_2011$Salary, Industry=salary_industry_2011$Industry), FUN = length)

```

```{r echo=FALSE}
#reorder the y axis before graphing
y_levels_2016 <- c("Unemployed", "Rather not say", "Other (please specify)", "Less than $10,000", "$10,000 - $20,000", "$20,000 - $30,000", "$30,000 - $40,000", "$40,000 - $50,000", "$50,000 - $60,000", "$60,000 - $70,000", "$70,000 - $80,000", "$80,000 - $90,000", "$90,000 - $100,000", "$100,000 - $110,000","$110,000 - $120,000", "$120,000 - $130,000", "$130,000 - $140,000","$140,000 - $150,000",  "$150,000 - $160,000","$160,000 - $170,000", "$170,000 - $180,000", "$180,000 - $190,000","$190,000 - $200,000", "More than $200,000")
y_levels_2015 <- c("Unemployed", "Rather not say", "Less than $20,000", "$20,000 - $40,000", "$40,000 - $60,000", "$60,000 - $80,000", "$80,000 - $100,000", "$100,000 - $120,000", "$120,000 - $140,000", "$140,000 - $160,000", "More than $160,000")
y_levels_2014 <- c("Student / Unemployed", "Rather not say", "<$20,000", "$20,000 - $40,000", "$40,000 - $60,000", "$60,000 - $80,000", "$80,000 - $100,000", "$100,000 - $120,000", "$120,000 - $140,000", ">$140,000")
y_levels_2013 <- y_levels_2014
y_levels_2012 <- y_levels_2014
y_levels_2011 <- c("Student / Unemployed", "<$20,000", "$20,000 - $40,000", "$40,000 - $60,000", "$60,000 - $80,000", "$80,000 - $100,000", "$100,000 - $120,000", "$120,000 - $140,000", ">$140,000")

si_agg_2016$Salary <- factor(si_agg_2016$Salary, levels = y_levels_2016)
si_agg_2015$Salary <- factor(si_agg_2015$Salary, levels = y_levels_2015)
si_agg_2014$Salary <- factor(si_agg_2014$Salary, levels = y_levels_2014)
si_agg_2013$Salary <- factor(si_agg_2013$Salary, levels = y_levels_2013)
si_agg_2012$Salary <- factor(si_agg_2012$Salary, levels = y_levels_2012)
si_agg_2011$Salary <- factor(si_agg_2011$Salary, levels = y_levels_2011)
  
```

```{r echo=FALSE}
ui <- fluidPage(
    titlePanel("Salary Per Industry"),
    tabsetPanel(
      tabPanel("2016", plotOutput("plot_2016")),
      tabPanel("2015", plotOutput("plot_2015")),
      tabPanel("2014", plotOutput("plot_2014")),
      tabPanel("2013", plotOutput("plot_2013")),
      tabPanel("2012", plotOutput("plot_2012")),
      tabPanel("2011", plotOutput("plot_2011"))
    )
)

server <- function(input, output, session) {
  

  output$plot_2016 <-  renderPlot({
    ggplot(si_agg_2016, aes(fill=Industry, y=si_agg_2016$x, x=si_agg_2016$Salary)) + geom_bar(stat="identity") + coord_flip() + labs(title = "Salary Per Industry", y = "Number of people", x = "Salary range")
    })
  
  output$plot_2015 <-  renderPlot({
    ggplot(si_agg_2015, aes(fill=Industry, y=si_agg_2015$x, x=si_agg_2015$Salary)) + geom_bar(stat="identity") + coord_flip() + labs(title = "Salary Per Industry", y = "Number of people", x = "Salary range")
    })
  
  output$plot_2014 <-  renderPlot({
    ggplot(si_agg_2014, aes(fill=Industry, y=si_agg_2014$x, x=si_agg_2014$Salary)) + geom_bar(stat="identity") + coord_flip() + labs(title = "Salary Per Industry", y = "Number of people", x = "Salary range")
    })
 
  output$plot_2013 <-  renderPlot({
    ggplot(si_agg_2013, aes(fill=Industry, y=si_agg_2013$x, x=si_agg_2013$Salary)) + geom_bar(stat="identity") + coord_flip() + labs(title = "Salary Per Industry", y = "Number of people", x = "Salary range")
    }) 
  
  output$plot_2012 <-  renderPlot({
    ggplot(si_agg_2012, aes(fill=Industry, y=si_agg_2012$x, x=si_agg_2012$Salary)) + geom_bar(stat="identity") + coord_flip() + labs(title = "Salary Per Industry", y = "Number of people", x = "Salary range")
    })
  
  output$plot_2011 <-  renderPlot({
    ggplot(si_agg_2011, aes(fill=Industry, y=si_agg_2011$x, x=si_agg_2011$Salary)) + geom_bar(stat="identity") + coord_flip() + labs(title = "Salary Per Industry", y = "Number of people", x = "Salary range")
    })
}

shinyApp(ui, server)
```

